channels:
- conda-forge
- bioconda
dependencies:
- python=3.6
- matplotlib=3.0.3
- snakemake=4.4.0
- click=6.7
- toml=0.9.4
- jupyter=1.0.0
- cmake=3.10.3
- openmpi=4.0.1
- gxx_linux-64=7.3.0
- libstdcxx-ng=9.1.0
- tclap=1.2.1
- hdf5=1.10.4
- h5py=2.9.0
- openmp=8.0.0
- pip:
    - pyabc==0.9.10
