time_points_up = 1000
time_range_up = [ 0, 20,]
time_points_down = 1000
time_range_down = [ 0, 10,]
parameter_points = 2000
parameter_range = [ -2, 3,]
optimum_normal = 0.0
optimum_treatment = 1.0
abc_min_epsilon = 0.1
abc_max_populations = 15
abc_min_acceptance = 0.0
abc_parallel_simulations = 1
abc_initial_population_size = 1000
mpi_simulations_per_time_point = 1000
mpi_cores_per_node = 2
mpi_max_population_size = 2000
mpi_death_rate = 0.1
mpi_max_time = 100000
mpi_noise_function_sigma = 0.6181551325310957
mpi_rate_function_center = 0.9962864327963825
mpi_rate_function_shape = 22.41992721348301
mpi_rate_function_width = 2.9252977195304126
