time_points_up = 10000
time_range_up = [0, 20]
time_points_down = 1000
time_range_down = [0, 10]
parameter_points = 1000
parameter_range = [-2, 3]
noise_sigma = 0.1
optimum_normal = 0.0
optimum_treatment = 1.0
abc_min_epsilon = 0.1
abc_max_populations = 15
abc_min_acceptance = 0.0
abc_parallel_simulations = 2